<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="maxwell">

  <xacro:property name="arm_height" value="0.2"/> <!-- deck to arm_link at max height-->
  <xacro:property name="column_height" value="0.258375" /> <!-- deck to top of 80/20 -->
  
  <xacro:include filename="$(find maxwell_defs)/urdf/hardware/ax12.xacro" />
  <xacro:include filename="$(find maxwell_defs)/urdf/hardware/rx64.xacro" />
  <xacro:include filename="$(find maxwell_defs)/urdf/sensors/xtion_camera.xacro" />
  
  <!-- The following included files set up definitions of parts of the robot body -->
  <xacro:include filename="$(find maxwell_defs)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find maxwell_defs)/urdf/torso.urdf.xacro" />
  <xacro:include filename="$(find maxwell_defs)/urdf/head.urdf.xacro" />
  <xacro:include filename="$(find maxwell_defs)/urdf/materials.urdf.xacro" />

  <!-- Now we can start using the macros included above to define the actual Maxwell -->
  <armadillo_base name="base" color="Orange"/>

  <!-- Add Torso Upright -->
  <maxwell_torso name="torso" parent="base_link">
    <origin xyz="-0.00635 0 ${base_size_z+arm_height}" rpy="0 0 0"/>
  </maxwell_torso>

  <!-- Head -->
  <maxwell_head name="head" parent="torso_link" color="Orange">
    <origin xyz="0 0 ${column_height-arm_height}" rpy="0 0 0"/>
  </maxwell_head>
  <xtion_camera name="head_camera" parent="head_tilt_link">
    <origin xyz="0 0 0.026" rpy="0 0 0"/>
  </xtion_camera>

</robot>
