<?xml version="1.0"?>
<robot>

  <macro name="maxwell_torso" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${column_height/2 - arm_height}" rpy="0 0 0 " />
        <geometry>
          <box size="0.0254 0.0254 ${column_height}"/>
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${column_height/2 - arm_height}" rpy="0 0 0 " />
        <geometry>
          <box size="0.0254 0.0254 ${column_height}"/>
        </geometry>
      </collision>
    </link>
  </macro>

</robot>
